\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@node Top
@top Top

@menu
* SmartCalc v10::
@end menu

@node SmartCalc v10
@chapter SmartCalc v1.0
@anchor{#smartcalc-v1.0}
Программа на языке C стандарта C11, используются компилятор gcc и
библиотека элементов интерфейса GTK+3

@node Программа имеет 2 режима
@anchor{#программа-имеет-2-режима}
@itemize
@item
Стандартный калькулятор (с функцией построения графика)
@item
Кредный калькудятор
@end itemize

@node Стандартный калькулятор
@anchor{#стандартный-калькулятор}
@itemize
@item
На вход программы подаются как целые числа, так и вещественные числа,
записанные через точку. Ввод чисел в экспоненциальной записи не
реализован.
@item
Вычисление производится после полного ввода вычисляемого выражения и
нажатия на кнопку @code{[=].}
@item
Вычисление произвольных скобочных арифметических выражений в инфиксной
нотации.
@item
Вычисление произвольных скобочных арифметических выражений в инфиксной
нотации с подстановкой значения переменной x в виде числа.
@item
Построение графика функции, заданной с помощью выражения в инфиксной
нотации с переменной @emph{x.}
@item
Область определения и область значения функций ограничиваются по крайней
мере числами от -1000000 до 1000000.
@item
Проверяемая точность дробной части - минимум 7 знаков после запятой.
@item
У пользователя есть возможность ввода до 255 символов.
@end itemize

@node Скобочные арифметические выражения в инфиксной нотации должны поддерживать следующие арифметические операции и математические функции
@anchor{#скобочные-арифметические-выражения-в-инфиксной-нотации-должны-поддерживать-следующие-арифметические-операции-и-математические-функции}
@itemize
@item
Арифметические операторы
@end itemize

@multitable @columnfractions 0.25 0.25 0.25 0.25 
@item 
Название оператора
 @tab Инфиксная нотация@*
(Классическая)
 @tab Префиксная нотация@*
(Польская нотация)
 @tab Постфиксная нотация@*
(Обратная польская нотация)
@item 
Скобки
 @tab (a + b)
 @tab (+ a b)
 @tab a b +
@item 
Сложение
 @tab a + b
 @tab + a b
 @tab a b +
@item 
Вычитание
 @tab a - b
 @tab - a b
 @tab a b -
@item 
Умножение
 @tab a * b
 @tab * a b
 @tab a b *
@item 
Деление
 @tab a / b
 @tab / a b
 @tab a b \
@item 
Возведение в степень
 @tab a ^ b
 @tab ^ a b
 @tab a b ^
@item 
Остаток от деления
 @tab a mod b
 @tab mod a b
 @tab a b mod
@item 
Унарный плюс
 @tab +a
 @tab +a
 @tab a+
@item 
Унарный минус
 @tab -a
 @tab -a
 @tab @multitable {a-} 
@item 
a-
@end multitable

@end multitable

@itemize
@item
Функции
@end itemize

@multitable {Вычисляет натуральный логарифм} {sqrt(x)} 
@item 
Описание функции
 @tab Функция
@item 
Вычисляет косинус
 @tab cos(x)
@item 
Вычисляет синус
 @tab sin(x)
@item 
Вычисляет тангенс
 @tab tan(x)
@item 
Вычисляет арккосинус
 @tab acos(x)
@item 
Вычисляет арксинус
 @tab asin(x)
@item 
Вычисляет арктангенс
 @tab atan(x)
@item 
Вычисляет квадратный корень
 @tab sqrt(x)
@item 
Вычисляет натуральный логарифм
 @tab ln(x)
@item 
Вычисляет десятичный логарифм
 @tab log(x)
@end multitable

@node Кредитный калькулятор
@anchor{#кредитный-калькулятор}
@itemize
@item
Вход: общая сумма кредита, срок, процентная ставка, тип (аннуитетный,
дифференцированный)
@item
Выход: ежемесячный платеж, переплата по кредиту, общая выплата
@end itemize

@bye